pipeline {
	
	agent {
    label 'docker' 
    }

	

    stages {
        stage('Build') {
		agent {
        docker {
          // Set both label and image
          label 'docker'
          image 'maven:3-alpine'
        }
      }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
			agent {
        docker {
          // Set both label and image
          label 'docker'
          image 'maven:3-alpine'
        }
      }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
